/**
 * Generated by NC UI Compiler v3.0
 * Source: nc-apps/stock-market/ui/stock_dashboard.ncui
 *
 * This file was compiled from NC UI plain English source.
 * It runs in any browser — no server, no Node.js, no NC runtime needed.
 * Deploy to GitHub Pages, Netlify, Vercel, or open index.html directly.
 *
 * HOW TO READ THIS FILE:
 *   Each page from the .ncui source becomes a `component` object below.
 *   The render() function returns a VNode tree (h() calls).
 *   NCUIRuntime.mount() drives reactivity, routing, and DOM updates.
 */

(function () {
  'use strict';

  const { h, hText, NCUIHelpers, NCUIValidation } = NCUIRuntime;
  const { string, count, sum, filter, format_currency, upper, truncate } = NCUIHelpers;

  // ════════════════════════════════════════════════════════════
  //  ACTIONS — compiled from NC UI `action` blocks
  // ════════════════════════════════════════════════════════════

  async function loadQuote(comp) {
    const symbol = comp.read('symbol');
    comp.write('loading', true);
    comp.write('error', '');
    try {
      // In a real app: await comp.fetch('/api/quote/' + symbol, { auth: true })
      // Demo uses mock data so this works on GitHub Pages with no backend
      await new Promise(r => setTimeout(r, 600)); // simulate network
      const mockQuote = {
        symbol: symbol.toUpperCase(),
        price:  (100 + Math.random() * 900).toFixed(2),
        change: ((Math.random() - 0.5) * 10).toFixed(2),
        changePercent: ((Math.random() - 0.5) * 5).toFixed(2),
        volume: Math.floor(Math.random() * 10000000),
        marketCap: '$' + (Math.random() * 2000).toFixed(0) + 'B',
        high:   (100 + Math.random() * 900).toFixed(2),
        low:    (100 + Math.random() * 900).toFixed(2),
        open:   (100 + Math.random() * 900).toFixed(2),
      };
      comp.write('quote', mockQuote);
      comp.write('searched', true);
    } catch (e) {
      comp.write('error', 'Failed to load quote: ' + e.message);
    } finally {
      comp.write('loading', false);
    }
  }

  async function loadPortfolio(comp) {
    comp.write('portfolio_loading', true);
    await new Promise(r => setTimeout(r, 400));
    comp.write('portfolio', [
      { symbol: 'NVDA', shares: 50,  avgCost: 380.00, currentPrice: 875.30, change: +2.4 },
      { symbol: 'AAPL', shares: 100, avgCost: 150.00, currentPrice: 189.50, change: +0.8 },
      { symbol: 'MSFT', shares: 75,  avgCost: 280.00, currentPrice: 415.20, change: +1.2 },
      { symbol: 'TSLA', shares: 30,  avgCost: 200.00, currentPrice: 175.80, change: -3.1 },
      { symbol: 'AMZN', shares: 40,  avgCost: 170.00, currentPrice: 192.40, change: +1.8 },
    ]);
    comp.write('portfolio_loading', false);
  }

  // ════════════════════════════════════════════════════════════
  //  PAGES — compiled from NC UI `page` blocks
  // ════════════════════════════════════════════════════════════

  // ── Home / Dashboard Page ─────────────────────────────────
  const pageDashboard = {
    name: 'dashboard',
    title: 'NeuralEdge — AI Stock Intelligence',
    state: {
      symbol:           'NVDA',
      quote:            null,
      loading:          false,
      error:            '',
      searched:         false,
      portfolio:        [],
      portfolio_loading: false,
    },
    onMount: async function (comp) {
      await loadPortfolio(comp);
      await loadQuote(comp);
    },
    render(comp) {
      const quote    = comp.read('quote');
      const loading  = comp.read('loading');
      const error    = comp.read('error');
      const symbol   = comp.read('symbol');
      const searched = comp.read('searched');
      const portfolio = comp.read('portfolio');
      const portLoading = comp.read('portfolio_loading');

      const isUp = quote && parseFloat(quote.change) >= 0;

      return h('div', { class: 'ncui-app' },
        // ── Header ─────────────────────────────────────────
        h('header', { class: 'ncui-header' },
          h('div', { class: 'ncui-header-inner' },
            h('div', { class: 'ncui-logo' },
              h('span', { class: 'ncui-logo-icon' }, hText('⚡')),
              h('span', { class: 'ncui-logo-text' }, hText('NeuralEdge'))
            ),
            h('nav', { class: 'ncui-nav' },
              h('a', { href: '#/', class: 'ncui-nav-link active' }, hText('Dashboard')),
              h('a', { href: '#/portfolio', class: 'ncui-nav-link' }, hText('Portfolio')),
              h('a', { href: '#/screener', class: 'ncui-nav-link' }, hText('Screener')),
            ),
            h('div', { class: 'ncui-header-tag' },
              h('span', { class: 'ncui-badge ncui-badge-success' }, hText('AI LIVE'))
            )
          )
        ),

        // ── Main Content ──────────────────────────────────
        h('main', { class: 'ncui-main' },

          // Hero Section
          h('section', { class: 'ncui-hero' },
            h('div', { class: 'ncui-hero-inner' },
              h('h1', { class: 'ncui-hero-title' }, hText('AI Stock Intelligence')),
              h('p', { class: 'ncui-hero-sub' },
                hText('Real-time quotes, AI predictions, portfolio analysis — powered by NC')
              ),

              // Search Bar
              h('div', { class: 'ncui-search-bar' },
                h('input', {
                  class: 'ncui-search-input',
                  type: 'text',
                  value: symbol,
                  placeholder: 'Enter ticker (NVDA, AAPL, TSLA...)',
                  oninput: (e) => comp.write('symbol', e.target.value.toUpperCase()),
                  onkeydown: (e) => { if (e.key === 'Enter') loadQuote(comp); },
                }),
                h('button', {
                  class: 'ncui-btn ncui-btn-primary',
                  onclick: () => loadQuote(comp),
                  disabled: loading,
                }, hText(loading ? 'Loading...' : 'Get Quote'))
              )
            )
          ),

          // Error
          error ? h('div', { class: 'ncui-container' },
            h('div', { class: 'ncui-alert ncui-alert-error' }, hText(error))
          ) : null,

          // Loading spinner
          loading ? h('div', { class: 'ncui-loading' },
            h('div', { class: 'ncui-spinner' })
          ) : null,

          // Quote Card
          !loading && searched && quote ? h('div', { class: 'ncui-container' },
            h('div', { class: 'ncui-card ncui-quote-card' },
              h('div', { class: 'ncui-quote-header' },
                h('div', {},
                  h('h2', { class: 'ncui-quote-symbol' }, hText(quote.symbol)),
                  h('p', { class: 'ncui-quote-name' }, hText('Real-time Quote'))
                ),
                h('div', { class: 'ncui-quote-price-block' },
                  h('div', { class: 'ncui-quote-price' }, hText('$' + quote.price)),
                  h('div', {
                    class: 'ncui-quote-change ' + (isUp ? 'up' : 'down')
                  }, hText((isUp ? '▲ +' : '▼ ') + quote.change + ' (' + quote.changePercent + '%)'))
                )
              ),
              h('div', { class: 'ncui-quote-stats' },
                h('div', { class: 'ncui-stat' },
                  h('span', { class: 'ncui-stat-label' }, hText('Open')),
                  h('span', { class: 'ncui-stat-value' }, hText('$' + quote.open))
                ),
                h('div', { class: 'ncui-stat' },
                  h('span', { class: 'ncui-stat-label' }, hText('High')),
                  h('span', { class: 'ncui-stat-value up' }, hText('$' + quote.high))
                ),
                h('div', { class: 'ncui-stat' },
                  h('span', { class: 'ncui-stat-label' }, hText('Low')),
                  h('span', { class: 'ncui-stat-value down' }, hText('$' + quote.low))
                ),
                h('div', { class: 'ncui-stat' },
                  h('span', { class: 'ncui-stat-label' }, hText('Volume')),
                  h('span', { class: 'ncui-stat-value' }, hText(
                    quote.volume > 1000000
                      ? (quote.volume / 1000000).toFixed(1) + 'M'
                      : quote.volume.toLocaleString()
                  ))
                ),
                h('div', { class: 'ncui-stat' },
                  h('span', { class: 'ncui-stat-label' }, hText('Mkt Cap')),
                  h('span', { class: 'ncui-stat-value' }, hText(quote.marketCap))
                ),
              ),
              h('div', { class: 'ncui-ai-tag' },
                h('span', {}, hText('⚡ AI Analysis: ')),
                h('span', { class: 'ncui-ai-insight' }, hText(
                  isUp
                    ? 'Bullish momentum detected. Strong institutional buying.'
                    : 'Bearish pressure. Watch support levels closely.'
                ))
              )
            )
          ) : null,

          // Quick Actions
          h('div', { class: 'ncui-container' },
            h('div', { class: 'ncui-quick-actions' },
              ...[
                { symbol: 'NVDA',  label: 'NVIDIA',    badge: 'AI' },
                { symbol: 'AAPL',  label: 'Apple',     badge: 'TECH' },
                { symbol: 'TSLA',  label: 'Tesla',     badge: 'EV' },
                { symbol: 'MSFT',  label: 'Microsoft', badge: 'CLOUD' },
                { symbol: 'AMZN',  label: 'Amazon',    badge: 'RETAIL' },
                { symbol: 'META',  label: 'Meta',      badge: 'SOCIAL' },
              ].map(stock =>
                h('button', {
                  class: 'ncui-quick-btn',
                  onclick: () => { comp.write('symbol', stock.symbol); loadQuote(comp); }
                },
                  h('span', { class: 'ncui-quick-symbol' }, hText(stock.symbol)),
                  h('span', { class: 'ncui-quick-label'  }, hText(stock.label)),
                  h('span', { class: 'ncui-badge ncui-badge-info ncui-quick-badge' }, hText(stock.badge))
                )
              )
            )
          ),

          // Portfolio Table
          h('div', { class: 'ncui-container' },
            h('div', { class: 'ncui-card' },
              h('h3', { class: 'ncui-card-title' }, hText('Portfolio')),
              portLoading
                ? h('div', { class: 'ncui-loading' }, h('div', { class: 'ncui-spinner' }))
                : h('table', { class: 'ncui-table' },
                    h('thead', {},
                      h('tr', {},
                        h('th', {}, hText('Symbol')),
                        h('th', {}, hText('Shares')),
                        h('th', {}, hText('Avg Cost')),
                        h('th', {}, hText('Price')),
                        h('th', {}, hText('Value')),
                        h('th', {}, hText('Gain/Loss')),
                      )
                    ),
                    h('tbody', {},
                      ...portfolio.map(pos => {
                        const value = pos.shares * pos.currentPrice;
                        const cost  = pos.shares * pos.avgCost;
                        const gain  = value - cost;
                        const gainPct = ((gain / cost) * 100).toFixed(2);
                        const isGain = gain >= 0;
                        return h('tr', {},
                          h('td', {}, h('strong', {}, hText(pos.symbol))),
                          h('td', {}, hText(pos.shares)),
                          h('td', {}, hText('$' + pos.avgCost.toFixed(2))),
                          h('td', {}, hText('$' + pos.currentPrice.toFixed(2))),
                          h('td', {}, hText('$' + value.toFixed(0))),
                          h('td', { class: isGain ? 'up' : 'down' },
                            hText((isGain ? '+' : '') + '$' + gain.toFixed(0) + ' (' + gainPct + '%)')
                          )
                        );
                      })
                    )
                  )
            )
          )
        ),

        // ── Footer ───────────────────────────────────────
        h('footer', { class: 'ncui-footer' },
          h('p', {}, hText('© 2026 DevHeal Labs AI — Built with NC UI (plain English, no HTML)'))
        )
      );
    }
  };

  // ════════════════════════════════════════════════════════════
  //  APP DEFINITION — compiled from NC UI app declaration
  // ════════════════════════════════════════════════════════════

  const app = {
    name:    'NeuralEdge',
    version: '2.0.0',

    // Global state (empty — all state is page-local here)
    state: {},

    // Themes — compiled from NC UI `theme` blocks
    themes: {
      dark: {
        primary:    '#6366f1',
        secondary:  '#8b5cf6',
        background: '#0a0a0a',
        surface:    '#111111',
        text:       '#ffffff',
        'text-muted': '#888888',
        border:     '#222222',
      }
    },
    defaultTheme: 'dark',

    // Auth config (no auth required for this public demo)
    auth: {},

    // Router mode: 'hash' is required for GitHub Pages
    // GitHub Pages serves index.html for all routes with hash routing
    routerMode: 'hash',

    // Routes — compiled from NC UI `routes` block
    routes: [
      { pattern: '/',          component: pageDashboard, public: true },
      { pattern: '/dashboard', component: pageDashboard, public: true },
    ],
  };

  // ── Mount the app ────────────────────────────────────────
  NCUIRuntime.mount(app, '#app');

})();
